### ISSUE TITLE
The document link is broken

### ISSUE THREAD

**Issue by andrewc-arm** [ARMmbed/mbed-cli#951] opened 2020-02-05 08:08 UTC
In this document (https://github.com/ARMmbed/mbed-cli/blob/master/README.rst), there is a text line.

> The best way to get started is to [read the documentation on GitHub](https://github.com/ARMmbed/mbed-cli/blob/master/README.md).

This link is broken.

**Comment by ciarmcom** [comment] 2020-02-05 13:06
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-557*

**Comment by mark-edgeworth** [comment] 2020-02-12 14:18
This looks like a duplicate of https://github.com/ARMmbed/mbed-cli/issues/946

**Closed by mark-edgeworth** 2020-02-12 14:18 UTC
Labels: Jira status: OPEN, mirrored, type: bug
