### ISSUE TITLE
Creating a new program for mbed OS 2, the mbed library isn't downloaded

### ISSUE THREAD

**Issue by eavelardev** [ARMmbed/mbed-cli#436] opened 2017-02-15 20:18 UTC
macOS Sierra
mbed 1.0.0

When I create a new mbed OS 2 program the mbed library isn't downloaded automatically. I execute `mbed update` inside the project folder to resolve.

**Comment by screamerbg** [comment] 2017-02-22 12:06
@eavelardev What command do you use?

**Comment by eavelardev** [comment] 2017-02-22 22:05
I use `mbed new my_project_name --mbedlib`

**Comment by screamerbg** [comment] 2017-02-28 10:59
Hi,

I just used `mbed new <program> --mbedlib` and worked fine. Here is the output


```
D:\1>mbed --version
1.0.0

D:\1>mbed new test-classic --mbedlib
[mbed] Creating new program "test-classic" (git)
[mbed] Adding library "mbed" from "https://mbed.org/users/mbed_official/code/mbed/builds" at latest revision in the current branch
[mbed] Downloading library build "ef9c61f8c49f" (might take a minute)
[mbed] Unpacking library build "ef9c61f8c49f" in "D:\1\test-classic\mbed"
[mbed] Updating reference "mbed" -> "https://mbed.org/users/mbed_official/code/mbed/builds/ef9c61f8c49f"
[mbed] Couldn't find build tools in your program. Downloading the mbed 2.0 SDK tools...
```

**Comment by screamerbg** [comment] 2017-03-08 13:55
@eavelardev bump

**Comment by screamerbg** [comment] 2017-06-21 03:58
Closing as we're not able to reproduce. Please reopen if needed.

**Comment by michaelVisimid** [comment] 2018-02-27 20:58
The issue still exists with version 1.4. This is pretty easily reproduced and still an issue. After you changed to your test program's directory you should have either run tree to see that the mbed libraries are not downloaded, or added a main.cpp which would have showed you the exact same thing. I'm not quite sure how the recreate steps taken would have recreated the issue as at no point were the libraries actually checked for. Below is the output from the command prompt where I should that the issue still exists and that adding main.cpp and importing mbed-dev allows the program to compile. For that matter, why doesn't the CLI create a bare minimum main.cpp that looks something like this:

`#include "mbed.h"

int main() {
    while(1) {      
    }
}

`
Here is the command prompt output which is easily recreated with the use of either tree or attempting to compile with main.cpp. 

`C:\Users\mbaker\Desktop\test>py -2.7 -m mbed --version
1.4.0

C:\Users\mbaker\Desktop\test>py -2.7 -m mbed new test-classic --mbedlib
[mbed] Creating new program "test-classic" (git)
[mbed] Adding library "mbed" from "https://mbed.org/users/mbed_official/code/mbed/builds" at latest revision in the current branch
[mbed] Updating reference "mbed" -> "https://mbed.org/users/mbed_official/code/mbed/builds/tip"
warning: LF will be replaced by CRLF in mbed.bld.
The file will have its original line endings in your working directory.
[mbed] Couldn't find build tools in your program. Downloading the mbed 2.0 SDK tools...

C:\Users\mbaker\Desktop\test>cd test-classic

C:\Users\mbaker\Desktop\test\test-classic>tree
Folder PATH listing
Volume serial number is FA05-9E87
C:.
├───.temp
│   └───tools
│       ├───.hg
│       │   ├───cache
│       │   └───store
│       │       └───data
│       │           ├───arm__pack__manager
│       │           ├───bootloaders
│       │           │   ├───_m_t_s___d_r_a_g_o_n_f_l_y___f411_r_e
│       │           │   ├───_m_t_s___m_d_o_t___f411_r_e
│       │           │   └───_r_e_a_l_t_e_k___r_t_l8195_a_m
│       │           ├───buildbot
│       │           ├───ci__templates
│       │           │   ├───library__build
│       │           │   └───tests__build
│       │           ├───compliance
│       │           ├───config
│       │           ├───data
│       │           │   └───rpc
│       │           ├───dev
│       │           ├───export
│       │           │   ├───atmelstudio
│       │           │   ├───cdt
│       │           │   ├───cmsis
│       │           │   ├───codered
│       │           │   ├───coide
│       │           │   ├───ds5__5
│       │           │   ├───e2studio
│       │           │   ├───embitz
│       │           │   ├───gnuarmeclipse
│       │           │   ├───iar
│       │           │   ├───kds
│       │           │   ├───lpcxpresso
│       │           │   ├───makefile
│       │           │   ├───mcuxpresso
│       │           │   ├───qtcreator
│       │           │   ├───simplicity
│       │           │   ├───sw4stm32
│       │           │   ├───uvision
│       │           │   ├───vscode
│       │           │   └───zip
│       │           ├───git__hooks
│       │           ├───host__tests
│       │           │   ├───example
│       │           │   └───host__tests__plugins
│       │           ├───misc
│       │           ├───profiles
│       │           ├───targets
│       │           ├───test
│       │           │   ├───build__api
│       │           │   ├───config
│       │           │   ├───config__test
│       │           │   │   ├───test01
│       │           │   │   ├───test02
│       │           │   │   ├───test03
│       │           │   │   ├───test04
│       │           │   │   ├───test05
│       │           │   │   ├───test06
│       │           │   │   │   └───lib1
│       │           │   │   │       └───lib2
│       │           │   │   ├───test07
│       │           │   │   │   └───lib1
│       │           │   │   │       └───lib2
│       │           │   │   ├───test08
│       │           │   │   │   └───lib1
│       │           │   │   │       └───lib2
│       │           │   │   ├───test09
│       │           │   │   │   └───lib1
│       │           │   │   │       └───lib2
│       │           │   │   ├───test10
│       │           │   │   │   └───lib1
│       │           │   │   │       └───lib2
│       │           │   │   ├───test11
│       │           │   │   │   └───lib1
│       │           │   │   │       └───lib2
│       │           │   │   ├───test12
│       │           │   │   │   └───lib1
│       │           │   │   │       └───lib2
│       │           │   │   ├───test13
│       │           │   │   │   ├───lib1
│       │           │   │   │   └───lib2
│       │           │   │   ├───test14
│       │           │   │   ├───test15
│       │           │   │   │   └───lib1
│       │           │   │   ├───test16
│       │           │   │   │   ├───lib1
│       │           │   │   │   └───lib2
│       │           │   │   ├───test17
│       │           │   │   │   ├───lib1
│       │           │   │   │   └───lib2
│       │           │   │   ├───test18
│       │           │   │   │   ├───lib1
│       │           │   │   │   └───lib2
│       │           │   │   ├───test19
│       │           │   │   ├───test20
│       │           │   │   │   └───lib1
│       │           │   │   ├───test21
│       │           │   │   ├───test22
│       │           │   │   │   └───lib1
│       │           │   │   ├───test23
│       │           │   │   │   ├───lib1
│       │           │   │   │   └───lib2
│       │           │   │   ├───test24
│       │           │   │   │   ├───_f_e_a_t_u_r_e___i_p_v4
│       │           │   │   │   │   └───lib1
│       │           │   │   │   ├───_f_e_a_t_u_r_e___i_p_v6
│       │           │   │   │   │   └───lib2
│       │           │   │   │   └───_f_e_a_t_u_r_e___s_t_o_r_a_g_e
│       │           │   │   │       └───lib2
│       │           │   │   ├───test25
│       │           │   │   │   ├───_f_e_a_t_u_r_e___i_p_v6
│       │           │   │   │   │   ├───lib2
│       │           │   │   │   │   └───_f_e_a_t_u_r_e___i_p_v4
│       │           │   │   │   │       └───lib1
│       │           │   │   │   └───_f_e_a_t_u_r_e___s_t_o_r_a_g_e
│       │           │   │   │       ├───lib2
│       │           │   │   │       └───_f_e_a_t_u_r_e___i_p_v4
│       │           │   │   │           └───lib1
│       │           │   │   ├───test26
│       │           │   │   │   ├───_f_e_a_t_u_r_e___i_p_v4
│       │           │   │   │   │   └───lib1
│       │           │   │   │   ├───_f_e_a_t_u_r_e___i_p_v6
│       │           │   │   │   │   └───lib2
│       │           │   │   │   └───_f_e_a_t_u_r_e___s_t_o_r_a_g_e
│       │           │   │   │       └───lib2
│       │           │   │   ├───test27
│       │           │   │   │   └───lib1
│       │           │   │   └───test28
│       │           │   ├───examples
│       │           │   ├───export
│       │           │   ├───memap
│       │           │   ├───targets
│       │           │   ├───test__api
│       │           │   └───toolchains
│       │           └───toolchains
│       ├───arm_pack_manager
│       ├───bootloaders
│       │   ├───MTS_DRAGONFLY_F411RE
│       │   ├───MTS_MDOT_F411RE
│       │   └───REALTEK_RTL8195AM
│       ├───config
│       ├───data
│       │   └───rpc
│       ├───export
│       │   ├───atmelstudio
│       │   ├───cdt
│       │   ├───cmsis
│       │   ├───coide
│       │   ├───ds5_5
│       │   ├───e2studio
│       │   ├───embitz
│       │   ├───gnuarmeclipse
│       │   ├───iar
│       │   ├───kds
│       │   ├───lpcxpresso
│       │   ├───makefile
│       │   ├───mcuxpresso
│       │   ├───qtcreator
│       │   ├───simplicity
│       │   ├───sw4stm32
│       │   ├───uvision
│       │   ├───vscode
│       │   └───zip
│       ├───git_hooks
│       ├───host_tests
│       │   ├───example
│       │   └───host_tests_plugins
│       ├───profiles
│       ├───targets
│       └───toolchains
└───mbed
    └───.bld

C:\Users\mbaker\Desktop\test\test-classic>py -2.7 -m mbed compile -m  NUCLEO_L073RZ -t  GCC_ARM
Building project test-classic (NUCLEO_L073RZ, GCC_ARM)
Scan: .
Scan: env
Scan: mbed
Link: test-classic
c:/program files (x86)/gnu tools arm embedded/7 2017-q4-major/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/lib/thumb/v6-m/crt0.o: In function `_start':
(.text+0x4e): undefined reference to `__wrap_main'
(.text+0x52): undefined reference to `__wrap_exit'
collect2.exe: error: ld returned 1 exit status
[ERROR] c:/program files (x86)/gnu tools arm embedded/7 2017-q4-major/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/lib/thumb/v6-m/crt0.o: In function `_start':
(.text+0x4e): undefined reference to `__wrap_main'
(.text+0x52): undefined reference to `__wrap_exit'
collect2.exe: error: ld returned 1 exit status

[mbed] ERROR: "C:\Python27\python.exe" returned error code 1.
[mbed] ERROR: Command "C:\Python27\python.exe -u C:\Users\mbaker\Desktop\test\test-classic\.temp\tools\make.py -t GCC_ARM -m NUCLEO_L073RZ --source . --build .\BUILD\NUCLEO_L073RZ\GCC_ARM" in "C:\Users\mbaker\Desktop\test\test-classic"
---

C:\Users\mbaker\Desktop\test\test-classic>py -2.7 -m mbed compile -m  NUCLEO_L073RZ -t  GCC_ARM
Building project test-classic (NUCLEO_L073RZ, GCC_ARM)
Scan: .
Scan: env
Scan: mbed
Compile [100.0%]: main.cpp
[Fatal Error] main.cpp@1,10: mbed.h: No such file or directory
[ERROR] .\main.cpp:1:10: fatal error: mbed.h: No such file or directory
 #include "mbed.h"
          ^~~~~~~~
compilation terminated.

[mbed] ERROR: "C:\Python27\python.exe" returned error code 1.
[mbed] ERROR: Command "C:\Python27\python.exe -u C:\Users\mbaker\Desktop\test\test-classic\.temp\tools\make.py -t GCC_ARM -m NUCLEO_L073RZ --source . --build .\BUILD\NUCLEO_L073RZ\GCC_ARM" in "C:\Users\mbaker\Desktop\test\test-classic"
---

C:\Users\mbaker\Desktop\test\test-classic>py -2.7 -m mbed add http://os.mbed.com/users/mbed_official/code/mbed-dev/
[mbed] Adding library "mbed-dev" from "https://os.mbed.com/users/mbed_official/code/mbed-dev" at latest revision in the current branch
[mbed] Updating reference "mbed-dev" -> "https://os.mbed.com/users/mbed_official/code/mbed-dev/#57724642e740"
warning: LF will be replaced by CRLF in mbed-dev.lib.
The file will have its original line endings in your working directory.

C:\Users\mbaker\Desktop\test\test-classic>py -2.7 -m mbed compile -m  NUCLEO_L073RZ -t  GCC_ARM
Building project test-classic (NUCLEO_L073RZ, GCC_ARM)
Scan: .
Scan: env
Scan: mbed
Compile [  0.7%]: main.cpp
Compile [  1.3%]: BusIn.cpp
Compile [  2.0%]: AnalogIn.cpp
Compile [  2.7%]: BusInOut.cpp
Compile [  3.4%]: CAN.cpp
Compile [  4.0%]: BusOut.cpp
Compile [  4.7%]: FlashIAP.cpp
Compile [  5.4%]: Ethernet.cpp
Compile [  6.0%]: I2CSlave.cpp
Compile [  6.7%]: InterruptManager.cpp
Compile [  7.4%]: I2C.cpp
Compile [  8.1%]: InterruptIn.cpp
Compile [  8.7%]: SPISlave.cpp
Compile [  9.4%]: RawSerial.cpp
Compile [ 10.1%]: Serial.cpp
Compile [ 10.7%]: SPI.cpp
Compile [ 11.4%]: Ticker.cpp
Compile [ 12.1%]: Timer.cpp
Compile [ 12.8%]: SerialBase.cpp
Compile [ 13.4%]: Timeout.cpp
Compile [ 14.1%]: TimerEvent.cpp
Compile [ 14.8%]: UARTSerial.cpp
Compile [ 15.4%]: mbed_gpio.c
Compile [ 16.1%]: mbed_flash_api.c
Compile [ 16.8%]: mbed_lp_ticker_api.c
Compile [ 17.4%]: mbed_sleep_manager.c
Compile [ 18.1%]: mbed_pinmap_common.c
Compile [ 18.8%]: mbed_ticker_api.c
Compile [ 19.5%]: mbed_us_ticker_api.c
Compile [ 20.1%]: CallChain.cpp
Compile [ 20.8%]: FileBase.cpp
Compile [ 21.5%]: ATCmdParser.cpp
Compile [ 22.1%]: FileHandle.cpp
Compile [ 22.8%]: FileSystemHandle.cpp
Compile [ 23.5%]: FilePath.cpp
Compile [ 24.2%]: LocalFileSystem.cpp
Compile [ 24.8%]: mbed_application.c
Compile [ 25.5%]: Stream.cpp
Compile [ 26.2%]: mbed_assert.c
Compile [ 26.8%]: mbed_alloc_wrappers.cpp
Compile [ 27.5%]: mbed_board.c
Compile [ 28.2%]: mbed_error.c
Compile [ 28.9%]: mbed_critical.c
Compile [ 29.5%]: mbed_interface.c
Compile [ 30.2%]: mbed_mktime.c
Compile [ 30.9%]: mbed_poll.cpp
Compile [ 31.5%]: mbed_retarget.cpp
Compile [ 32.2%]: mbed_mem_trace.cpp
Compile [ 32.9%]: mbed_rtc_time.cpp
Compile [ 33.6%]: mbed_stats.c
Compile [ 34.2%]: mbed_sdk_boot.c
Compile [ 34.9%]: mbed_semihost_api.c
Compile [ 35.6%]: mbed_wait_api_rtos.cpp
Compile [ 36.2%]: mbed_wait_api_no_rtos.c
Compile [ 36.9%]: startup_stm32l073xx.S
Compile [ 37.6%]: PeripheralPins.c
Compile [ 38.3%]: system_clock.c
Compile [ 38.9%]: analogout_device.c
Compile [ 39.6%]: analogin_device.c
Compile [ 40.3%]: stm32l0xx_hal.c
Compile [ 40.9%]: stm32l0xx_hal_comp_ex.c
Compile [ 41.6%]: stm32l0xx_hal_adc.c
Compile [ 42.3%]: stm32l0xx_hal_comp.c
Compile [ 43.0%]: stm32l0xx_hal_adc_ex.c
Compile [ 43.6%]: stm32l0xx_hal_cryp.c
Compile [ 44.3%]: stm32l0xx_hal_crc_ex.c
Compile [ 45.0%]: stm32l0xx_hal_cortex.c
Compile [ 45.6%]: stm32l0xx_hal_crc.c
[Warning] stm32l0xx_hal_crc.c@493,8: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
[Warning] stm32l0xx_hal_crc.c@497,8: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
[Warning] stm32l0xx_hal_crc.c@527,8: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
Compile [ 46.3%]: stm32l0xx_hal_cryp_ex.c
Compile [ 47.0%]: stm32l0xx_hal_dac.c
Compile [ 47.7%]: stm32l0xx_hal_dac_ex.c
Compile [ 48.3%]: stm32l0xx_hal_dma.c
Compile [ 49.0%]: stm32l0xx_hal_firewall.c
Compile [ 49.7%]: stm32l0xx_hal_flash_ramfunc.c
Compile [ 50.3%]: stm32l0xx_hal_flash.c
Compile [ 51.0%]: stm32l0xx_hal_flash_ex.c
Compile [ 51.7%]: stm32l0xx_hal_gpio.c
Compile [ 52.3%]: stm32l0xx_hal_i2c_ex.c
Compile [ 53.0%]: stm32l0xx_hal_i2s.c
Compile [ 53.7%]: stm32l0xx_hal_i2c.c
Compile [ 54.4%]: stm32l0xx_hal_iwdg.c
Compile [ 55.0%]: stm32l0xx_hal_irda.c
Compile [ 55.7%]: stm32l0xx_hal_lptim.c
Compile [ 56.4%]: stm32l0xx_hal_lcd.c
Compile [ 57.0%]: stm32l0xx_hal_pcd_ex.c
Compile [ 57.7%]: stm32l0xx_hal_pwr.c
Compile [ 58.4%]: stm32l0xx_hal_pwr_ex.c
Compile [ 59.1%]: stm32l0xx_hal_pcd.c
Compile [ 59.7%]: stm32l0xx_hal_rcc_ex.c
Compile [ 60.4%]: stm32l0xx_hal_rcc.c
Compile [ 61.1%]: stm32l0xx_hal_rtc.c
Compile [ 61.7%]: stm32l0xx_hal_rng.c
Compile [ 62.4%]: stm32l0xx_hal_smartcard_ex.c
Compile [ 63.1%]: stm32l0xx_hal_rtc_ex.c
Compile [ 63.8%]: stm32l0xx_hal_smbus.c
Compile [ 64.4%]: stm32l0xx_hal_smartcard.c
Compile [ 65.1%]: stm32l0xx_hal_tim_ex.c
Compile [ 65.8%]: stm32l0xx_hal_tsc.c
Compile [ 66.4%]: stm32l0xx_hal_spi.c
Compile [ 67.1%]: stm32l0xx_hal_tim.c
Compile [ 67.8%]: stm32l0xx_hal_wwdg.c
Compile [ 68.5%]: stm32l0xx_hal_uart_ex.c
Compile [ 69.1%]: stm32l0xx_hal_uart.c
Compile [ 69.8%]: stm32l0xx_hal_usart.c
Compile [ 70.5%]: stm32l0xx_ll_adc.c
Compile [ 71.1%]: stm32l0xx_ll_crc.c
Compile [ 71.8%]: stm32l0xx_ll_comp.c
Compile [ 72.5%]: stm32l0xx_ll_crs.c
Compile [ 73.2%]: stm32l0xx_ll_dac.c
Compile [ 73.8%]: stm32l0xx_ll_exti.c
Compile [ 74.5%]: stm32l0xx_ll_dma.c
Compile [ 75.2%]: stm32l0xx_ll_gpio.c
Compile [ 75.8%]: stm32l0xx_ll_pwr.c
Compile [ 76.5%]: stm32l0xx_ll_i2c.c
Compile [ 77.2%]: stm32l0xx_ll_lptim.c
Compile [ 77.9%]: stm32l0xx_ll_lpuart.c
Compile [ 78.5%]: stm32l0xx_ll_rtc.c
Compile [ 79.2%]: stm32l0xx_ll_rcc.c
Compile [ 79.9%]: stm32l0xx_ll_spi.c
Compile [ 80.5%]: stm32l0xx_ll_rng.c
Compile [ 81.2%]: stm32l0xx_ll_tim.c
Compile [ 81.9%]: stm32l0xx_ll_usart.c
Compile [ 82.6%]: stm32l0xx_ll_utils.c
Compile [ 83.2%]: system_stm32l0xx.c
Compile [ 83.9%]: gpio_irq_device.c
Compile [ 84.6%]: flash_api.c
Compile [ 85.2%]: serial_device.c
[Warning] serial_device.c@49,15: inline function 'get_uart_index' declared but never defined
Compile [ 85.9%]: pwmout_device.c
Compile [ 86.6%]: can_api.c
Compile [ 87.2%]: spi_api.c
Compile [ 87.9%]: analogout_api.c
Compile [ 88.6%]: analogin_api.c
Compile [ 89.3%]: gpio_api.c
Compile [ 89.9%]: hal_tick_16b.c
Compile [ 90.6%]: gpio_irq_api.c
Compile [ 91.3%]: hal_tick_32b.c
Compile [ 91.9%]: mbed_overrides.c
Compile [ 92.6%]: i2c_api.c
Compile [ 93.3%]: pinmap.c
Compile [ 94.0%]: lp_ticker.c
Compile [ 94.6%]: port_api.c
Compile [ 95.3%]: pwmout_api.c
Compile [ 96.0%]: serial_api.c
Compile [ 96.6%]: rtc_api.c
Compile [ 97.3%]: sleep.c
Compile [ 98.0%]: trng_api.c
Compile [ 98.7%]: stm_spi_api.c
[Warning] stm32l0xx_ll_spi.h@1133,3: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
Compile [ 99.3%]: us_ticker_16b.c
Compile [100.0%]: us_ticker_32b.c
Link: test-classic
Elf2Bin: test-classic
+----------------------------------------------------------------------------------------------------------------+-------+-------+------+
| Module                                                                                                         | .text | .data | .bss |
+----------------------------------------------------------------------------------------------------------------+-------+-------+------+
| [fill]                                                                                                         |    25 |     4 |    9 |
| [lib]/c.a                                                                                                      | 26539 |  2472 |   89 |
| [lib]/gcc.a                                                                                                    |  8716 |     0 |    0 |
| [lib]/misc                                                                                                     |   220 |    12 |   28 |
| main.o                                                                                                         |     2 |     0 |    0 |
| mbed-dev\drivers\I2C.o                                                                                         |    18 |     0 |    0 |
| mbed-dev\drivers\SPI.o                                                                                         |   118 |     4 |  100 |
| mbed-dev\hal\mbed_gpio.o                                                                                       |    76 |     0 |    0 |
| mbed-dev\hal\mbed_pinmap_common.o                                                                              |   214 |     0 |    0 |
| mbed-dev\hal\mbed_ticker_api.o                                                                                 |   813 |     0 |    0 |
| mbed-dev\hal\mbed_us_ticker_api.o                                                                              |    68 |     4 |   64 |
| mbed-dev\platform\mbed_alloc_wrappers.o                                                                        |    32 |     0 |    0 |
| mbed-dev\platform\mbed_assert.o                                                                                |    85 |     0 |    0 |
| mbed-dev\platform\mbed_board.o                                                                                 |   202 |     0 |    0 |
| mbed-dev\platform\mbed_critical.o                                                                              |   264 |     0 |    5 |
| mbed-dev\platform\mbed_error.o                                                                                 |    44 |     0 |    1 |
| mbed-dev\platform\mbed_retarget.o                                                                              |   674 |     4 |  264 |
| mbed-dev\platform\mbed_sdk_boot.o                                                                              |    68 |     0 |    0 |
| mbed-dev\platform\mbed_wait_api_no_rtos.o                                                                      |    44 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\TARGET_STM32L0\TARGET_NUCLEO_L073RZ\PeripheralPins.o                               |   276 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\TARGET_STM32L0\TARGET_NUCLEO_L073RZ\device\TOOLCHAIN_GCC_ARM\startup_stm32l073xx.o |   246 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\TARGET_STM32L0\TARGET_NUCLEO_L073RZ\device\system_clock.o                          |   432 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\TARGET_STM32L0\device\stm32l0xx_hal.o                                              |    62 |     0 |    4 |
| mbed-dev\targets\TARGET_STM\TARGET_STM32L0\device\stm32l0xx_hal_rcc.o                                          |  1824 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\TARGET_STM32L0\device\stm32l0xx_hal_rcc_ex.o                                       |   416 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\TARGET_STM32L0\device\stm32l0xx_hal_tim.o                                          |   270 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\TARGET_STM32L0\device\stm32l0xx_hal_uart.o                                         |  1159 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\TARGET_STM32L0\device\system_stm32l0xx.o                                           |   173 |     4 |    0 |
| mbed-dev\targets\TARGET_STM\TARGET_STM32L0\serial_device.o                                                     |    72 |     0 |  560 |
| mbed-dev\targets\TARGET_STM\gpio_api.o                                                                         |   439 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\hal_tick_16b.o                                                                     |   328 |     0 |    4 |
| mbed-dev\targets\TARGET_STM\mbed_overrides.o                                                                   |    20 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\pinmap.o                                                                           |   509 |     0 |    0 |
| mbed-dev\targets\TARGET_STM\serial_api.o                                                                       |   952 |     0 |   80 |
| mbed-dev\targets\TARGET_STM\us_ticker_16b.o                                                                    |   202 |     0 |   64 |
| Subtotals                                                                                                      | 45602 |  2504 | 1272 |
+----------------------------------------------------------------------------------------------------------------+-------+-------+------+
Total Static RAM memory (data + bss): 3776 bytes
Total Flash memory (text + data): 48106 bytes

Image: .\BUILD\NUCLEO_L073RZ\GCC_ARM\test-classic.bin

C:\Users\mbaker\Desktop\test\test-classic>tree
`

I have omitted the final tree output because it is quite long since importing mbed-dev imports the configuration for every mbed board.

**Comment by theotherjimmy** [comment] 2018-02-27 21:17
@screamerbg I think the comment above provides ample steps to reproduce to open this issue.

**Comment by michaelVisimid** [comment] 2018-02-27 22:58
mbed-os programs have the same bug.

**Comment by screamerbg** [comment] 2018-05-26 11:26
@michaelVisimid @eavelardev I managed to reproduce the issue. Fix is on its way.

**Comment by screamerbg** [comment] 2018-05-26 11:31
@eavelardev @michaelVisimid PR #680 is now available which address this issue. Could you please try it and let me know if that fixes it for you as well?

**Comment by ciarmcom** [comment] 2018-06-06 15:51
ARM Internal Ref: MBOTRIAGE-463

**Comment by screamerbg** [comment] 2018-06-18 19:59
This is now tracked in #698

**Closed by screamerbg** 2018-06-18 19:59 UTC
Labels: bug, in progress, mirrored, re-check
