### ISSUE TITLE
Updating to v1.0 breaks mbed CLI in Linux

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-cli#399] opened 2016-11-23 09:47 UTC
Just upgraded the tool as shown below:

```
xxx@mlnx:~/mbed$ sudo pip install mbed-cli --upgrade
The directory '/home/xxx/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/xxx/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting mbed-cli
  Downloading mbed-cli-1.0.0.zip (50kB)
    100% |████████████████████████████████| 51kB 1.6MB/s 
Installing collected packages: mbed-cli
  Found existing installation: mbed-cli 0.9.10
    Uninstalling mbed-cli-0.9.10:
      Successfully uninstalled mbed-cli-0.9.10
  Running setup.py install for mbed-cli ... done
Successfully installed mbed-cli-1.0.0
xxx@mlnx:~/mbed$ mbed
bash: /home/xxx/.local/bin/mbed: No such file or directory
```

Tried to uninstall and install again, but same problem persists.

```
$ python --version
Python 2.7.12
$ pip --version
pip 9.0.1 from /home/xxx/.local/lib/python2.7/site-packages (python 2.7)
$ lsb_release -a
Description:	Ubuntu 16.04.1 LTS
```

@screamerbg

**Comment by screamerbg** [comment] 2016-11-25 08:20
Duplicate of #364

**Closed by screamerbg** 2016-11-25 08:20 UTC
Labels: duplicate
