### ISSUE TITLE
config toolchain - need to list options

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-cli#306] opened 2016-08-02 06:53 UTC
## Problem

nowhere in the mbed-cli help menus does it list what the acceptable options are for `mbed config toolchain`
## Solution
1. add a complete list to the help flavor text for toolchain
2. add tab completion and allow user to cycle thorugh list with tab completion

**Comment by BlackstoneEngineering** [comment] 2016-08-02 06:53
I think @theotherjimmy has some pending PR's that would make tab completion rediculously simple to add.

**Comment by theotherjimmy** [comment] 2016-08-02 13:54
Well, no. It's nowhere near ridiculously simple.

**Comment by screamerbg** [comment] 2016-08-03 09:01
Tab completion is a duplicate of https://github.com/ARMmbed/mbed-cli/issues/241. Please read @mjs-arm and @bremoran's comments.

**Comment by BlackstoneEngineering** [comment] 2016-08-03 09:37
Oi, dont close this, this is a super valid bug! This bug isnt about addint tab completion, its about adding a way to easily specify the toolchain. The other ticket is about git, which is wrapping another tool, this is about our own provided options.

**Comment by screamerbg** [comment] 2016-08-03 09:46
```
$ mbed toolchain -h
usage: mbed toolchain [-h] [-G] [-S] [-v] [-vv] [name]

Set or get default toolchain
This is an alias to 'mbed config [--global] toolchain [name]'

positional arguments:
  name                 Default toolchain name. Example: ARM, uARM, GCC_ARM, IAR
```

**Comment by theotherjimmy** [comment] 2017-11-28 20:41
Closing, as "a way to easily specify toolchain" is already present, as shown above.

**Closed by theotherjimmy** 2017-11-28 20:41 UTC
Labels: duplicate, future
