### ISSUE TITLE
Building on Windows is significantly slower than on Mac/Linux

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-cli#563] opened 2017-11-11 04:20 UTC
I've seen it at my VM, and also at some folks here at Korea IoT hackathon. Building on Windows is way slower, it seems to pause in between files... Are we doing some heavy hard disk activity in between?

Same machine, in Linux VM it goes very fast.

**Comment by theotherjimmy** [comment] 2017-11-13 15:53
>  way slower

Do you have any numbers on this? Does this affect mbed lib the same amount as Mbed OS?

> it seems to pause in between files

We print those status messages after each compile job finishes. I'm hesitant to say that the Mbed OS tools are to blame here, as the compiler could be slow and that would have exactly the same symptoms.

>  Are we doing some heavy hard disk activity in between?

We are not. The compiler (armcc/iccarm/gcc) probably is (there are many header files to include).

I have noticed this before, but I was not able to root cause it.

**Comment by theotherjimmy** [comment] 2017-11-13 15:54
Oh, FYI, Mbed CLI accounts for about 300ms the execution time of any job on my machine. I think if this is something we can solve, we are going to have to solve it in the Mbed OS Tools.

**Comment by bridadan** [comment] 2017-11-13 16:09
@janjongboom I've noticed this as well.

My laptop runs Windows 10 and has a 4 core CPU. Compiling blinky with GCC_ARM, ARM, and IAR all average 1 minute and 30 seconds.

On the same laptop, I run an Ubuntu Server VM that only has 2 cores allocated to it. With GCC_ARM, blinky compiled in just under seconds, a full minute faster. For fun I tried using the ARM compiler on Linux as well, but that took 1 minute and 30 seconds. I think this was mostly due to the network license in use.

@theotherjimmy To rule out our Python tools, would using the Makefile exporter be a good way to get closer to just the raw compiler calls?

**Comment by theotherjimmy** [comment] 2017-11-13 17:13
Using the makefile exporter with -j <num-cpus> would show if it's the compiler or not.

**Comment by janjongboom** [comment] 2017-11-15 19:40
@theotherjimmy @bridadan make is also slow on my Windows VM, but it might be that the virus scanner that IT put on that machine is to blame. It's just interesting to see that Brian sees it too, wonder what the underlying issue is; and if we can solve it somehow.

**Comment by bridadan** [comment] 2017-11-15 19:46
I have tried on my home Windows machine with Mbed CLI and it was slow as well, though I also have a virus scanner on that machine. It'd be worth trying it on a clean machine with both Mbed CLI and Make. If we're still seeing slow performance, maybe the compiler team can help us out?

**Comment by theotherjimmy** [comment] 2017-11-15 19:46
The makefile was also slow, so it's probably the compiler we are running that is causing the slowdown. Running the compiler is required, so I'm not sure that there is much we can do here.

**Comment by theotherjimmy** [comment] 2017-11-15 19:47
Aside from bug the compiler team. For IAR and GCC_ARM though, it might not be as easy

**Comment by theotherjimmy** [comment] 2017-11-28 16:53
@janjongboom @bridadan I'm going to close this, as I don't think there is anything we can do about it. Please feel free to re-open it if you can come up with a path to resolving it.

**Closed by theotherjimmy** 2017-11-28 16:53 UTC

**Comment by kins-dev** [comment] 2020-01-29 19:14
Well, a good portion of the issue is from compiling a single file at a time.  Windows has some major overhead when starting processes.  Limit the number of processes you spawn and your Windows builds will get faster.

**Comment by boraozgen** [comment] 2020-09-23 14:28
@kins-dev Can you explain what you mean by limiting the number of processes?

**Comment by kins-dev** [comment] 2020-09-23 15:24
Well it has been a while, but what I remember is this:
For each file to compile
Create a new python process
That python process then calls either a shell or gcc directly (which is 1 or 2 additional create process calls depending on how it was set up)
For literally thousands of files

Most of the items are not even applicable to your particular design, but that's a different issue.  So let's look at bench marking around the web comparing Linux fork+exec to create process:
<https://www.bitsnbites.eu/benchmarking-os-primitives/>
If you scroll down to launching programs, you'll see Windows shows between one and two orders of magnitude in difference in creating a new process.  Some of this maybe Windows defender as noted, but that's a standard way of setting up a system.

Unfortunately there doesn't seem to be a good second source I could find quickly of numbers.  On the plus side, these are relatively recent in terms of system setup and OS used.

One of the major differences is fork+exec is handled by the kernel.  It optimized to work quickly, because well the Linux kernel is 25,000,000+ lines of code, split among mostly small files.  <https://www.phoronix.com/scan.php?page=news_item&px=Linux-Kernel-Commits-2017>  Given how make works, and that the kernel was broken down by options to make, each unit is compiled to library and then linked together.  (At least this was the case, I haven't rebuilt my own kernel for a number of years.)  This is very similar to what mbed does.

Windows on the other hand does not have a kernel level system call for starting a new process.  It has an API call.  Further, that API call can be hooked into by debuggers, anti-virus and security (certificate checks and revocation) processes.

A side note:
Something similar also happens when you use the API to open a file, which is how an on access scanner is able to check a file for a virus before it is loaded into memory.)  Simply put Windows was never optimized to handle lots of small files.  You can see that today.  Copy 10,000 1k files by themselves, it takes forever.  Put them in a zip file with 0 compression, you get orders of magnitude in performance gain, despite both being of the same size.  There are all kinds of reasons why, but the point is windows handles small files badly.

So there's two things I think I see that could help out.  The first is to move from creating a new python process for each compilation unit to using threads inside python.  This may not help as much as expected though, I think python does something sneaky to try and keep the process overhead down.  The second is to specify multiple files to gcc and make larger libraries to link together.

**Comment by boraozgen** [comment] 2020-09-23 15:42
Thanks for the info! Didn't know much of this.

Your suggestions seem to be very fundamental to the build system. Maybe Mbed guys can take these into consideration when they are developing the new CMake based build system.

**Comment by BalenMars** [comment] 2021-04-24 16:54
Just wished to test a blinky using mbed,  an absolute disaster! My laptop with 4 cores, 32GB, running at full speed, the fan's screeming, then I check the task manger, I see python all over! No wonder why it's soooo slow!

**Comment by 0xc0170** [comment] 2021-04-26 08:14
> Just wished to test a blinky using mbed, an absolute disaster! My laptop with 4 cores, 32GB, running at full speed, the fan's screeming, then I check the task manger, I see python all over! No wonder why it's soooo slow!

Please test with mbed-cli 2 (updated to use CMake), it should be better.
