### ISSUE TITLE
mbed-cli always doing some Auto-installing which can be slow

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-cli#749] opened 2018-09-07 14:07 UTC
With mbed-cli 1.8.0 I always get this trace:

[mbed] Auto-installing missing Python modules...

I have installed the latest mbed-os/requirements.txt files so there should be no such step needed.

**Comment by theotherjimmy** [comment] 2018-09-07 14:42
The "check that you have all the deps" thing may not be perfect. I see this on my mac, but not my Linux box. Weird...

**Comment by theotherjimmy** [comment] 2018-09-07 14:42
What's your system like?
 * OS
 * Python version

**Comment by ciarmcom** [comment] 2018-09-07 15:49
ARM Internal Ref: MBOTRIAGE-1608

**Comment by teetak01** [comment] 2018-09-10 06:03
Python 2.7.12, Ubuntu 16.04

**Comment by maclobdell** [comment] 2018-09-10 18:35
I see this same issue on Windows.  Every time I issue a compile command it results in this, even though I also have the requirements all installed.

```
[mbed] Auto-installing missing Python modules...
```

**Comment by SeppoTakalo** [comment] 2018-09-13 12:42
Autoinstalling also break some Pip environments, as reported here: https://github.com/ARMmbed/mbed-cli/issues/754

**Comment by screamerbg** [comment] 2018-09-13 12:45
Fix was released in Mbed CLI 1.8.1. Could you update and try to reproduce the issue?

**Comment by mtvg** [comment] 2018-11-09 18:08
Also having the issue on Mac (10.13.6) with mbed-cli 1.8.2, Python 2.7.15, pip 18.0

**Comment by mtvg** [comment] 2018-11-12 22:02
Works for me with 1.8.3. Thanks!

**Comment by Ronny-Liu** [comment] 2018-11-15 12:49
Works for me with 1.8.3. Thanks!

**Comment by korjaa** [comment] 2019-01-08 10:15
I had custom icetea installed on my machine with:
```
cd icetea
python setup.py develop
```
now that I ran tried to run `mbed compile` it auto-installed it's own icetea on top of the development version and now neither one of them work.

```
$ mbed --version
1.8.3
```

**Comment by korjaa** [comment] 2019-01-08 10:16
This auto-installation is very frustrating feature.

**Comment by korjaa** [comment] 2019-01-08 10:18
Seems to relate to https://github.com/ARMmbed/mbed-cli/issues/795

**Comment by SeppoTakalo** [comment] 2019-01-08 10:18
’RM -rf mbes-os/requirements.txt’ should help.

**Comment by bridadan** [comment] 2019-01-08 16:36
I would like to remove the need to install these requirements in the future. However, this is difficult to do while the Mbed OS build system is still present alongside the source code.

**Comment by loverdeg-ep** [comment] 2019-01-08 16:40
>  while the Mbed OS build system is still present alongside the source code.

Tell me more.

**Comment by screamerbg** [comment] 2019-01-08 16:49
@bridadan There will always be some instalation of modules regardless whether the build system is part of the os or as an external tools package. Unless we're taking about integrating and packaging icetea and any other python dependency together in one large tools package for the os.

**Comment by theotherjimmy** [comment] 2019-01-08 17:31
@screamerbg If the build system and other python scripts are no longer part of the OS, then the requirements.txt will move here (into Mbed CLI) and dependencies would be installed up front.

**Comment by flit** [comment] 2019-02-26 20:26
I was seeing this bug prior to 1.8.3 on macOS 10.14.3. After updating to 1.8.3, I can confirm that it's fixed.

**Comment by ItsNageeK** [comment] 2019-08-20 03:25
Having this issue, mbed 1.10.0, macOS 10.14.4, python 2.7.14, pip 19.2.2, `pip install -r requirements.txt` continues to display the "missing Python modules..." any suggestions?

**Comment by mark-edgeworth** [comment] 2019-08-20 08:33
We think this issue will be resolved with the next release of the mbed-cli tools package which were are working on now.

**Comment by ciarmcom** [comment] 2019-10-31 17:29
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment] 2019-11-01 12:19
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment] 2019-11-13 16:37
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-472*

**Comment by mark-edgeworth** [comment] 2019-12-04 09:05
No further work planned on this.

**Closed by mark-edgeworth** 2019-12-04 09:05 UTC
Labels: Jira status: OPEN, in progress, mirrored, type: bug
