### ISSUE TITLE
When I use mbed tools for my experiment, there is some errors as follows. 

### ISSUE THREAD

**Issue by oneway3124** [ARMmbed/mbed-cli#669] opened 2018-05-13 09:20 UTC
![i
mage](https://user-images.githubusercontent.com/3787176/39965746-9ed522b6-56d1-11e8-9a53-03a14b7c8e5c.png)
```
C:\Users\dav\Desktop\ML-KWS-for-MCU\Deployment>mbed new kws_simple_test --mbedli
b
[mbed] Creating new program "kws_simple_test" (git)
[mbed] Adding library "mbed" from "https://mbed.org/users/mbed_official/code/mbe
d/builds" at latest revision in the current branch
[mbed] Updating reference "mbed" -> "https://mbed.org/users/mbed_official/code/m
bed/builds/tip"
warning: LF will be replaced by CRLF in mbed.bld.
The file will have its original line endings in your working directory.
[mbed] Couldn't find build tools in your program. Downloading the mbed 2.0 SDK t
ools...
[mbed] ERROR: Unknown Error: 'module' object has no attribute 'get_installed_dis
tributions'
---
```

**Comment by screamerbg** [comment] 2018-05-13 12:58
Hello. This is caused by breaking changes in pip10. Please update mbed CLI to latest (1.5.1) or pip to version 9 or below.

**Comment by oneway3124** [comment] 2018-05-14 09:07
OK, I will try it .

**Comment by oneway3124** [comment] 2018-05-14 09:25
![image](https://user-images.githubusercontent.com/3787176/39989014-77e492de-579b-11e8-9a6f-39c1b23cbd97.png)
Hello , the pip version has been down to 9.0.0, and the mbed-cli is 1.1.1, but the error information donot change . How to do it in the next step?
Try pip version 10 and mbed cli 1.5.1 later?

**Comment by oneway3124** [comment] 2018-05-14 09:26
reopen it

**Comment by bridadan** [comment] 2018-05-14 16:03
> Try pip version 10 and mbed cli 1.5.1 later?

Yup, please go ahead and update both packages. You seem to be on a pretty old version of mbed-cli any way, so updating both to the latest is probably a good path forward. Let us know if you run into any other issues!

**Comment by oneway3124** [comment] 2018-05-14 16:07
C:\Users\Administrator\Desktop\ML-KWS-for-MCU\Deployment>mbed new kws_simple_tes
t --mbedlib
[mbed] Creating new program "kws_simple_test" (git)
[mbed] Adding library "mbed" from "https://mbed.org/users/mbed_official/code/mbe
d/builds" at latest revision in the current branch
[mbed] Updating reference "mbed" -> "https://mbed.org/users/mbed_official/code/m
bed/builds/tip"
warning: LF will be replaced by CRLF in mbed.bld.
The file will have its original line endings in your working directory.
[mbed] Couldn't find build tools in your program. Downloading the mbed 2.0 SDK t
ools...

C:\Users\Administrator\Desktop\ML-KWS-for-MCU\Deployment>cd kws_simple_test

C:\Users\Administrator\Desktop\ML-KWS-for-MCU\Deployment\kws_simple_test>mbed de
ploy
[mbed] Updating library "mbed" to branch/tag "tip"
[mbed] Downloading library build "5aab5a7997ee" (might take a minute)

**Comment by oneway3124** [comment] 2018-05-14 16:09
"xxx might take a minute " actually cost about one hour, I donot know why?

**Comment by bridadan** [comment] 2018-05-14 16:16
That step will depend greatly on your internet connection speed. I don't know the exact size of that library but I think its quite large.

But it sounds like mbed-cli is now functioning correctly for you? If that's the case, would you mind closing this issue? If you encounter other problems, feel free to raise a different issue!

**Comment by oneway3124** [comment] 2018-05-16 05:44
If the exact size of that library is quite large , can I download it manually?

**Comment by oneway3124** [comment] 2018-05-23 08:44
Maybe the information is resulted from the "mbed deploy".
 
![image](https://user-images.githubusercontent.com/3787176/40413467-74dd6bba-5ea8-11e8-9b08-5d0112d4b1b7.png)
@bridadan @screamerbg

**Comment by screamerbg** [comment] 2018-05-26 10:07
@oneway3124 Here's how you could download it manually.
Step 1. Go to Mbed OS 2 releases and choose a revision - https://os.mbed.com/users/mbed_official/code/mbed/graph/
Step 2. Click on revision of your choice, e.g. https://os.mbed.com/users/mbed_official/code/mbed/rev/4f6c30876dfa/
Step 3. In the URL, change `rev` to `archive` and append `zip`, e.g. From https://os.mbed.com/users/mbed_official/code/mbed/rev/4f6c30876dfa/ change to https://os.mbed.com/users/mbed_official/code/mbed/archive/4f6c30876dfa/zip

Hope this helps. Please close the issue if this solved your problem

**Comment by ciarmcom** [comment] 2018-06-06 15:50
ARM Internal Ref: MBOTRIAGE-444

**Comment by theotherjimmy** [comment] 2018-06-14 14:31
@screamerbg Should we add that information in a troubleshooting section somewhere? @oneway3124 Where would you expect to find the above method for downloading the mbed library manually, if we put it in the handbook?

**Closed** 2018-09-27 16:52 UTC
Labels: mirrored, question
