### ISSUE TITLE
link in Readme.rst broken 

### ISSUE THREAD

**Issue by Reissner** [ARMmbed/mbed-cli#953] opened 2020-02-11 13:21 UTC
Link "read the documentation on GitHub" broken: results in page not found.

**Comment by ciarmcom** [comment] 2020-02-11 16:27
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-559*

**Comment by mark-edgeworth** [comment] 2020-02-12 14:18
This looks like a duplicate of https://github.com/ARMmbed/mbed-cli/issues/946

**Closed by mark-edgeworth** 2020-02-12 14:18 UTC
Labels: Jira status: OPEN, mirrored, type: bug
